#!/usr/bin/env bash
# script that transfers a file from our client to a server
if(( $# < 3 )) # "$#" checks the number of arguments
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/ # sudo would be needed if the checker does not execute the script as root user
fi
