#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect below requirements:
# - Install nginx on your web-01 server
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Holberton School
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R $USER:$USER /var/www/html/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
