#!/usr/bin/env bash
# script containing commands to automatically configure
# a "301 moved permanently" redirection
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
service nginx start
red="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "36i $red" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
