#!/usr/bin/env bash
# Bash script to install and configure HAproxy
sudo apt-get -y update
sudo apt-get install -y haproxy=1.6.\*
setup="
frontend firstbalance
	bind *:80
	mode http
	default_backend webservers

backend webservers
	balance roundrobin
	server 2103-web-01 34.74.134.187:80 check
	server 2103-web-02 34.74.176.2:80 check
"
echo "$setup" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
