#!/usr/bin/env bash
# Bash script to install and configure HAproxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get install -y haproxy=1.6.\*
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 2103-web-01 34.74.134.187:80 check\n\tserver 2103-web-02 34.74.176.2:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
