#!/usr/bin/env bash
# Bash script with the minimum number of commands to automate a fix
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm -f /var/run/nginx.pid
