#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
((i=1))
while((i <= 100))
do
    if((i % 3 == 0))
    then
        echo "Fizz"
    fi
    if((i % 5 == 0))
    then
        echo "Buzz"
    fi
    if((i % 3 == 0)) && ((i % 5 == 0))
    then
        echo "FizzBuzz"
    else
        echo "$i"
    fi
    ((i++))
done