#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times using while
# but for the 9th iteration, displays Holberton School and then Hi on a new line
((i=1))
while((i <= 10))
do
    if((i == 9))
    then
        echo "Holberton School"
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i++))
done