#!/usr/bin/env bash
# Bash script that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
ls > list
for i in "cat list"; do ls | cut -d "-" -f2-; ((i++)); done